title = "但如今"
baseURL = "https://www.johnzhang.org"
languageCode = "zh-cn"
theme = "ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "zh_CN"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "但如今，神的义在律法以外已经显明出来，有律法和先知为证。就是神的义，因信耶稣基督加给一切相信的人，并没有分别。因为世人都犯了罪，亏缺了神的荣耀，如今却蒙神的恩典，因基督耶稣的救赎，就白白地称义。 - 圣经·罗马书·三章二十一到二十四节"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 4
